apiVersion: v1
kind: Secret
metadata:
  name: {{ include "semantic-merge-request.fullname" . }}
  labels:
    {{- include "semantic-merge-request.labels" . | nindent 4 }}
type: Opaque
data:
  WEBHOOK_SECRET: {{ .Values.semanticGitlabApiConfigs.WEBHOOK_SECRET | b64enc | quote }}
  GITLAB_API_URL: {{ .Values.semanticGitlabApiConfigs.GITLAB_API_URL | b64enc | quote }}
